package Modelo;
// Generated 20-Mar-2019 16:32:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bien generated by hbm2java
 */
public class Bien  implements java.io.Serializable {


     private String numeroserie;
     private Solicitud solicitud;
     private String descripcion;
     private String marca;
     private String modelo;
     private double preciounitario;
     private int cantidad;
     private Set activos = new HashSet(0);

    public Bien() {
    }

	
    public Bien(String numeroserie, Solicitud solicitud, String descripcion, String marca, String modelo, double preciounitario, int cantidad) {
        this.numeroserie = numeroserie;
        this.solicitud = solicitud;
        this.descripcion = descripcion;
        this.marca = marca;
        this.modelo = modelo;
        this.preciounitario = preciounitario;
        this.cantidad = cantidad;
    }
    public Bien(String numeroserie, Solicitud solicitud, String descripcion, String marca, String modelo, double preciounitario, int cantidad, Set activos) {
       this.numeroserie = numeroserie;
       this.solicitud = solicitud;
       this.descripcion = descripcion;
       this.marca = marca;
       this.modelo = modelo;
       this.preciounitario = preciounitario;
       this.cantidad = cantidad;
       this.activos = activos;
    }
   
    public String getNumeroserie() {
        return this.numeroserie;
    }
    
    public void setNumeroserie(String numeroserie) {
        this.numeroserie = numeroserie;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public double getPreciounitario() {
        return this.preciounitario;
    }
    
    public void setPreciounitario(double preciounitario) {
        this.preciounitario = preciounitario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


