package Modelo;
// Generated 20-Mar-2019 16:32:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String tipo;
     private int codigoconsecutivo;
     private Set activos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String tipo, int codigoconsecutivo) {
        this.tipo = tipo;
        this.codigoconsecutivo = codigoconsecutivo;
    }
    public Categoria(String tipo, int codigoconsecutivo, Set activos) {
       this.tipo = tipo;
       this.codigoconsecutivo = codigoconsecutivo;
       this.activos = activos;
    }
   
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getCodigoconsecutivo() {
        return this.codigoconsecutivo;
    }
    
    public void setCodigoconsecutivo(int codigoconsecutivo) {
        this.codigoconsecutivo = codigoconsecutivo;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


