package Modelo;
// Generated 20-Mar-2019 16:32:39 by Hibernate Tools 4.3.1



/**
 * LaborId generated by hbm2java
 */
public class LaborId  implements java.io.Serializable {


     private String funcionarioId;
     private String dependenciaCodigodependecia;
     private String puestoIdpuesto;

    public LaborId() {
    }

    public LaborId(String funcionarioId, String dependenciaCodigodependecia, String puestoIdpuesto) {
       this.funcionarioId = funcionarioId;
       this.dependenciaCodigodependecia = dependenciaCodigodependecia;
       this.puestoIdpuesto = puestoIdpuesto;
    }
   
    public String getFuncionarioId() {
        return this.funcionarioId;
    }
    
    public void setFuncionarioId(String funcionarioId) {
        this.funcionarioId = funcionarioId;
    }
    public String getDependenciaCodigodependecia() {
        return this.dependenciaCodigodependecia;
    }
    
    public void setDependenciaCodigodependecia(String dependenciaCodigodependecia) {
        this.dependenciaCodigodependecia = dependenciaCodigodependecia;
    }
    public String getPuestoIdpuesto() {
        return this.puestoIdpuesto;
    }
    
    public void setPuestoIdpuesto(String puestoIdpuesto) {
        this.puestoIdpuesto = puestoIdpuesto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LaborId) ) return false;
		 LaborId castOther = ( LaborId ) other; 
         
		 return ( (this.getFuncionarioId()==castOther.getFuncionarioId()) || ( this.getFuncionarioId()!=null && castOther.getFuncionarioId()!=null && this.getFuncionarioId().equals(castOther.getFuncionarioId()) ) )
 && ( (this.getDependenciaCodigodependecia()==castOther.getDependenciaCodigodependecia()) || ( this.getDependenciaCodigodependecia()!=null && castOther.getDependenciaCodigodependecia()!=null && this.getDependenciaCodigodependecia().equals(castOther.getDependenciaCodigodependecia()) ) )
 && ( (this.getPuestoIdpuesto()==castOther.getPuestoIdpuesto()) || ( this.getPuestoIdpuesto()!=null && castOther.getPuestoIdpuesto()!=null && this.getPuestoIdpuesto().equals(castOther.getPuestoIdpuesto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFuncionarioId() == null ? 0 : this.getFuncionarioId().hashCode() );
         result = 37 * result + ( getDependenciaCodigodependecia() == null ? 0 : this.getDependenciaCodigodependecia().hashCode() );
         result = 37 * result + ( getPuestoIdpuesto() == null ? 0 : this.getPuestoIdpuesto().hashCode() );
         return result;
   }   


}


