package Modelo;
// Generated 20-Mar-2019 16:32:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private String idpuesto;
     private String descripcion;
     private Set labors = new HashSet(0);

    public Puesto() {
    }

	
    public Puesto(String idpuesto, String descripcion) {
        this.idpuesto = idpuesto;
        this.descripcion = descripcion;
    }
    public Puesto(String idpuesto, String descripcion, Set labors) {
       this.idpuesto = idpuesto;
       this.descripcion = descripcion;
       this.labors = labors;
    }
   
    public String getIdpuesto() {
        return this.idpuesto;
    }
    
    public void setIdpuesto(String idpuesto) {
        this.idpuesto = idpuesto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getLabors() {
        return this.labors;
    }
    
    public void setLabors(Set labors) {
        this.labors = labors;
    }




}


