package Modelo;
// Generated 20-Mar-2019 16:32:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer numsolicitud;
     private Dependencia dependencia;
     private Funcionario funcionario;
     private String numerocomprobante;
     private String tipoadquision;
     private Date fecha;
     private String estadosolicitud;
     private Set biens = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(Dependencia dependencia, Funcionario funcionario, String numerocomprobante, String tipoadquision, Date fecha, String estadosolicitud) {
        this.dependencia = dependencia;
        this.funcionario = funcionario;
        this.numerocomprobante = numerocomprobante;
        this.tipoadquision = tipoadquision;
        this.fecha = fecha;
        this.estadosolicitud = estadosolicitud;
    }
    public Solicitud(Dependencia dependencia, Funcionario funcionario, String numerocomprobante, String tipoadquision, Date fecha, String estadosolicitud, Set biens) {
       this.dependencia = dependencia;
       this.funcionario = funcionario;
       this.numerocomprobante = numerocomprobante;
       this.tipoadquision = tipoadquision;
       this.fecha = fecha;
       this.estadosolicitud = estadosolicitud;
       this.biens = biens;
    }
   
    public Integer getNumsolicitud() {
        return this.numsolicitud;
    }
    
    public void setNumsolicitud(Integer numsolicitud) {
        this.numsolicitud = numsolicitud;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNumerocomprobante() {
        return this.numerocomprobante;
    }
    
    public void setNumerocomprobante(String numerocomprobante) {
        this.numerocomprobante = numerocomprobante;
    }
    public String getTipoadquision() {
        return this.tipoadquision;
    }
    
    public void setTipoadquision(String tipoadquision) {
        this.tipoadquision = tipoadquision;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstadosolicitud() {
        return this.estadosolicitud;
    }
    
    public void setEstadosolicitud(String estadosolicitud) {
        this.estadosolicitud = estadosolicitud;
    }
    public Set getBiens() {
        return this.biens;
    }
    
    public void setBiens(Set biens) {
        this.biens = biens;
    }




}


