package Modelo;
// Generated 20-Mar-2019 16:32:39 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String id;
     private Funcionario funcionario;
     private String password;

    public Usuario() {
    }

	
    public Usuario(String id, Funcionario funcionario) {
        this.id = id;
        this.funcionario = funcionario;
    }
    public Usuario(String id, Funcionario funcionario, String password) {
       this.id = id;
       this.funcionario = funcionario;
       this.password = password;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


